### ISSUE TITLE
ADJUSTMENT NEEDED: Want to be able to create a help tab for each extension where I can output HTML

### ISSUE THREAD

**Issue by mervb** [mervb/Easy-Property-Listings#150]
This will let me output HTML and add instructions

![extensions help tab](https://cloud.githubusercontent.com/assets/4696393/8153312/77e1c95c-135e-11e5-801c-0eabc305235e.png)

**Comment by mediatelecom** [comment]
this has been done .. example help tab is added to staff directory

**Comment by mervb** [comment]
Remove the syntax highlighter that you added i just want to output instructions that accept the h1, h2 etc and p tags like we do on the Help page. I can use pre to highlight code. No need for syntax highlighting as cool as it is.
