### ISSUE TITLE
ADJUSTMENT NEEDED: Add OPTIONAL city field all post types && optional Country Display and search

### ISSUE THREAD

**Issue by mervb** [mervb/Easy-Property-Listings#162]
RE CORE: Need to add an OPTIONAL City Field
Have Country Field but no search options.

IN 2.2 update i've added State and PostCode search

this is for address display and search, not sure but think an additional taxonomy?

yes, BUT some places use Street, Suburb, City, State, PostCode, Country
[12:50:31 PM | Edited 12:50:42 PM] Merv Barrett: this will also need optional country display and search

**Comment by mervb** [comment]
FOR ALL CORE changes
use my https://github.com/mervb/Easy-Property-Listings/tree/2.2-feature-release
as a starting point.

name CORE branches 2.2-feature-{FEATURE-NAME} that will make it easier to merge for release

**Comment by mediatelecom** [comment]
done

**Comment by mervb** [comment]
Prefer Country to be a global setting not per listing.

![country setting](https://cloud.githubusercontent.com/assets/4696393/8562233/359f45e0-2562-11e5-9841-95b0b32b7eb7.png)

EG user in thailand may want to have the country on all listings shown. 

(Add country setting to Labels section)


Also extra space appearing before comma    , 
![extra space](https://cloud.githubusercontent.com/assets/4696393/8562218/0ea0f75e-2562-11e5-8b5f-5d0ec3d59655.png)
