### ISSUE TITLE
QUESTION: Ability to add uploadable files to a listing in the CORE

### ISSUE THREAD

**Issue by mervb** [mervb/Easy-Property-Listings#164]
need to be able to upload multiple PDF files to listings. However best to house the functions in the CORE so multiple extensions can use this upload file functionality.

We already have this in the brochure extension usable in the admin extension setting page for adding the image header. So already there i'm guessing

RE ACF as a base
-----------------------------------
to complicated
but do not continue from where you were
we DO not want ACF slow plugin

we are like iphone
you can have this in any colour as long as its black or can write PHP

**Comment by mervb** [comment]
i think we already have this as the brochure extension can upload the image header. just make sure its usable via custom fields too  in admin

**Comment by mervb** [comment]
PLEASE COMMENT RAJAT

**Comment by mediatelecom** [comment]
done
