### ISSUE TITLE
QUESTION: Add Search by status to Grid/List (Select date/price)

### ISSUE THREAD

**Issue by mervb** [mervb/Easy-Property-Listings#165]
http://easypropertylistings.com.au/support/topic/orderby-property_status/

When viewing properties I would like the available properties to show at the top of each list. Currently users have to search through numerous pages of ‘leased’ rentals which is not user friendly.

I assume I just need to add the query arg ‘orderby’ => ‘property_status’ somewhere, but I’m not sure where. I would like it to be ordered on search results and shortcode output if possible.

Thanks again for the great plugin!

**Comment by mervb** [comment]
Unsure about this change.

Its fine to add it to the main /property/ as there will be current/sold (only options we want)
or /rental/ current/leased (only options we want)

But what happens if user uses shortcode eg:

[listing post_type="property" status="current"] (then no need for the sort by current/sold
or
[listing post_type="property" status="sold"] (then no need for the sort by current/sold

So not sure, let me know if possible

**Comment by mediatelecom** [comment]
done

**Comment by mervb** [comment]
Still issue if using shortcode

EG [listing post_type="property" status="sold" limit="5" tools_top="on"]

This shows Current Sold/LEASED but should not because status="sold"
