### ISSUE TITLE
ADJUSTMENT NEEDED: Ability to add additional search fields to search widget and shortcode

### ISSUE THREAD

**Issue by mervb** [mervb/Easy-Property-Listings#167]
using a filter or hook. So a user can add a custom drop down list like the property_category and hook that into the widget/shortcode output some how.

http://easypropertylistings.com.au/support/topic/hook-for-adding-custom-search-fields/?view=all

**Comment by mervb** [comment]
The dropdown option was to become optional.

Actually you can put a setting in the Search Widget: Tab Labels to enable this... We have a section for the search widget

**Comment by mediatelecom** [comment]
done
