### ISSUE TITLE
ADJUSTMENT NEEDED: Confirm the display of the sold prices

### ISSUE THREAD

**Issue by mervb** [mervb/Easy-Property-Listings#168]

**Comment by mervb** [comment]
Sold Price adjustment in admin columns (rental does not have a sold price)

![sold price adjustment](https://cloud.githubusercontent.com/assets/4696393/8562139/1ad66366-2561-11e5-99f2-d769a80eb544.png)

**Comment by mediatelecom** [comment]
done

**Comment by mervb** [comment]
I must not have latest push or something
