### ISSUE TITLE
ADJUSTMENT NEEDED: search and Select Two Property Categories

### ISSUE THREAD

**Issue by mervb** [mervb/Easy-Property-Listings#169]
https://wordpress.org/support/topic/select-two-property-categories?replies=4

**Comment by mervb** [comment]
Not liking this.... This feature should be optional and not default. Only 1 request so its not for everyone... Use a hook/filter to enable this drop-down style

**Comment by mediatelecom** [comment]
done

**Comment by mervb** [comment]
Thought i asked for this, but possibly forgot

![search multiselect](https://cloud.githubusercontent.com/assets/4696393/8611871/485e897c-26fa-11e5-9542-63c2983fbe38.png)
