### ISSUE TITLE
EPL CRM adding to dashboard causing error

### ISSUE THREAD

**Issue by mervb** [mervb/Easy-Property-Listings#176]
I may have missed the code to fix this but consider the count will be different, see if core upgrade can facilitate extensions modifying this easily with their own counts

Add SD to this, number of staff members.

Add LP to this, number of location Profiles.

Add MR Number of listings etc

Add Testimonials

Perhaps a new slim variation for totals (or widget will be too big
|  4 Commercial (as is now)   | 0 Commercial land (as is now)     |
---------------------------------------------------
ICON Testimonials 22
----------------------------------------------------
ICON Staff Members 22
---------------------------------------------------
ICON Location Profiles 22
-----------------------------------------------------

**Comment by mervb** [comment]
![epl-dashboard-widget](https://cloud.githubusercontent.com/assets/4696393/8481078/c94dae24-2113-11e5-910f-f88d4cd4bcc1.png)

**Comment by mediatelecom** [comment]
fixed

**Comment by mervb** [comment]
unable to test, push CRM
