### ISSUE TITLE
Search by property_id not working

### ISSUE THREAD

**Issue by mervb** [mervb/Easy-Property-Listings#242]

**Comment by mervb** [comment]
Also the property_id is not always numeric, unsure how to search by ID and by the title in the same place

**Comment by mervb** [comment]
I think you have use post__in for the property_id search which is the WordPress post ID, we want to search by property_id

**Comment by mervb** [comment]
Lets stick with the numeric search for that, i've seen id's with eg 1212sdf4343 which the user can import into the title.

Just adjust the post__in to be a meta value search

**Comment by mediatelecom** [comment]
done
